language: ruby
rvm:
- 2.5.1
before_install:
- yes | sudo gem update --system --force
install:
- bundle update
- bundle install
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: WafAD2kcGEh2Jp/YdzLsWo2jv11qKNnzevPn8HaX8pPus6AEgpW6I/vB0l8qhVBHmmcTYMP3AUK8RnBgROeZIUe2xtljiyTua5W54LdCO2WdaOvVxDYzioDq4g3XOl+ykLbmmB6mfEfCvpNsX4V2kqUg3D3k4iKRlM8OUUqfVCKx2kAzEP+mtl824Uind689/IOF5Fpyb6N7SDID+6n4pG9o+DN1wYocr5Lyy3xNzpNjvtaAVU+tHObGcD9aHE+BVL/a1yE7FrYvZxZQgPxid9YGDvlFU/TiynUuGEeqL1JfoCwxVBzsLuy2+IwZbJpexCP4mnX+MO9l1CMY6BHY6sb1fIjsoGt93Q2bxGDOuKEJIZVLyakDOFKfqduyZ9c6NanMUn+l5NygOvOG14ZPkJpQ5vUP2YlXfPjnkZxbA9kd3x+bTd9k4HjF3KJu4EKkgdpMk7A+X7lEqiiyK2qmpbjUOLqfIp+z/1wDwl8lawmFod85yC0O3ZLC+bThwjhGwxq9ZNbDpAsJYBmaDgl3QFCE5O8LL3fIWACdGG7AQ10V8UC6u9Ljwt/v5EMMIdvXtlYvHm1y2hr16l3CwF1tUsHSaShKvef/c+7ObDdx9rZuw9Mh8vwJVkoAgfryAi2LA4PElpIxALcw48Aelvfu7VDgE7hcfEDfgVmL2+VVbYs=
exclude: [vendor]
cache: 
  directories:
    - vendor
sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: ${GH_TOKEN} # Set in the settings page of your repository, as a secure variable
  local_dir: _site
  on:
    branch: gh-pages

